name: projectname33

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^0.6.0
  path_provider: ^0.5.0+1
  provider: ^4.3.2+1
  http: ^0.12.0+4
  shared_preferences: ^0.5.10
  fluttertoast: ^7.0.4
  url_launcher: ^6.0.4
  http_parser: ^3.1.4
  image_picker: ^0.6.7+10
  dropdown_below: ^0.0.7
  google_maps_flutter: ^1.2.0
  flutter_polyline_points: ^0.2.4
  geolocator: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon.jpg
    - assets/picture.jpg
    - assets/images/logo_1.png
    - assets/images/shop.png
    - assets/images/no_image.png
    - assets/images/settings.jpg
    - assets/images/balance_cod.jpg
    - assets/images/size.png
    - assets/images/weight.png
    - assets/images/quantity.png
    - assets/images/call-icon.png
    - assets/images/chat-icon.png
    - assets/images/locationicon.png
    - assets/images/eye-icon.png
    - assets/images/strike-eye.png
    - assets/images/direction.png
    - assets/images/balance-icon.png
    - assets/images/cancel-icon.png
    - assets/images/report-icon.png
    - assets/images/location-icon.png
    - assets/images/homemade.jpg